version: "3.8"

services : 
    postgres:
        container_name: postgres
        image: postgres:latest
        ports: 
            - 5432:5432
        networks :
            - songapp-net
    redis:
        container_name: redis
        image: redis:latest
        ports: 
            - 6379:6379
        networks :
            - songapp-net
    lbp1-songapp:
        container_name: lbp1-songapp
        image: lbp1-songapp:1.0
        ports: 
            - 8080:8080
        depends_on :
            - postgres
            - redis
        environment: 
            - PGUSER=postgres
            - PGPASSWORD=123
            - PGDATABASE=postgres
            - PGHOST=localhost
            - PGPORT=5432
            - HOST=localhost
            - PORT=5000
            - ACCESS_TOKEN_KEY=780858d73bfc38580f9c6bd68aac0beb772eaea91bf7da11dfdc80ae2fa17dfe408380a5b8c574fec9beedfdce722771d05ddf9db1919efa5cf2da18548f9ff6
            - REFRESH_TOKEN_KEY=17a11ff1e2caa85b720ca35109f2ce552895bfadddfd6236322ba4b2fc476f35253667775cc1d46ec48040a720820b6b3014b919cb80ae9ebccaf97e9dfc9035
            - ACCESS_TOKEN_AGE=18000
            - RABBITMQ_SERVER=amqp://localhost
            - REDIS_SERVER=localhost
        networks:
            - songapp-net

networks:
    songapp-net :
        name: songapp-net
